### ISSUE TITLE
Manta M5P Hard Mounting

### ISSUE THREAD

**Issue by DerScorbus** [Alexander-T-Moss/Hex-Zero#6]
I had the DXF file, deck_panel_m5p, lasered. 
Is there a holder that you have to print to make it fit? Because the holes don't fit.
![IMG_4692](https://github.com/user-attachments/assets/036e1864-73d9-46e7-87a9-d28a7bd90838)

**Comment by Alexander-T-Moss** [comment]
Yes, there is supposed to be a printed mount, but it's got lost when I've updated the repo at some point from the looks of things, so I will find the mount again now and get it uploaded

**Comment by DerScorbus** [comment]
Perfect, thank you!

**Comment by Alexander-T-Moss** [comment]
So it appears that I've accidently removed all the hard mount printed parts (the ones you need).. oops..., so I've re-uploaded the ones for the M5P (link below) and will upload all the other ones now, good spot!

https://github.com/Alexander-T-Moss/Hex-Zero/tree/main/STLs/Electronics/Control_Boards/BTT_Manta_M5P

**Comment by Alexander-T-Moss** [comment]
Uploaded the missing STLs

**Comment by DerScorbus** [comment]
The STls you just uploaded to the M5P are no longer there.

**Comment by Alexander-T-Moss** [comment]
That's very weird... well I've re-re-uploaded them again so hopefully they don't magically disapear this time haha

**Comment by DerScorbus** [comment]
Haha, strange, I'd report back if it happens again
